apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/glass-tribute-471316-k1/annotation-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: HF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001